sudo: false
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  global:
    - CORE_BRANCH=master
    - APPNAME=contactsplus
  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

before_install:
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh $APPNAME $CORE_BRANCH $DB
  - cd ../core
  - php occ app:enable $APPNAME

before_script:
  - cd apps/$APPNAME

script:
  # Test lint
  - find . -name \*.php -not -path './vendor/*' -exec php -l "{}" \;

  # Run phpunit tests
  - cd tests
  - phpunit --configuration phpunit.xml

matrix:
  include:
    - php: 5.4
      env: DB=mysql
    - php: 5.4
      env: DB=pgsql

  allow_failures:
    - php: hhvm
    - php: 7
  fast_finish: true
